
---
   - name: install python-software-properties
     apt: pkg='python-software-properties' state=present

   - name: add nginx ppa 
     command: /usr/bin/add-apt-repository -y ppa:nginx/stable

   - name: update apt repo
     command: /usr/bin/apt-get update

   - name: install nginx
     apt: pkg=nginx state=present

     notify:
       - restart nginx
