
---
   - name: install python-software-properties
     apt: pkg='python-software-properties' state=present

   - name: "add nginx ppa if it ubuntu 10.04 and up"
     command: /usr/bin/add-apt-repository -y ppa:nginx/stable
      # only_if: '$is_ubuntu and $is_10_up'

   - name: update apt repo
     command: /usr/bin/apt-get update

   - name: install nginx
     apt: pkg=nginx state=present

     notify:
       - restart nginx
